name: CI/CD
on: [push]
jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest] # windows-latest, macOS-latest
        php-versions: ['5.4', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3', '8.4', '8.5', '8.6']
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: json #optional
          #ini-values: "post_max_size=256M" #optional
      - name: Install dependencies
        run: composer install
      - name: Show phpinfo as TEXT
        run: ./bin/phpinfo --text
      - name: Show phpinfo as JSON
        run: ./bin/phpinfo --json
